module.exports = [
	{ "name" : "Checkered", "description" : "Shared pieces" },
	{ "name" : "Zen", "description" : "Reverse captures" },
	{ "name" : "Atomic", "description" : "Explosive captures" },
	{ "name" : "Chess960", "description" : "Standard rules" },
//  { "name" : "AntiKing", "description" : "Keep anti-king in check" },
//  { "name" : "Magnetic", "description" : "Laws of attraction" },
//  { "name" : "Alice", "description" : "Both sides of the mirror" },
//  { "name" : "Cylindric", "description" : "Sides comunicate" },
//  { "name" : "Moscow", "description" : "Custom pieces setup" },
//  { "name" : "Grand", "description" : "Big board" },
//  { "name" : "Wildebeest", "description" : "Balanced sliders & leapers" },
//  { "name" : "Loser", "description" : "Lose all pieces" },
//  { "name" : "Shatranj", "description" : "Ancestral rules" },
//  { "name" : "Switching", "description" : "Exchange pieces positions" },
//  { "name" : "Absorption", "description" : "Capture enhance movements" },
//  { "name" : "Dark", "description" : "In the fog" },
//  { "name" : "Kriegspiel", "description" : "Blind war" },
];
