-- Re-run this script after variants are added

insert or ignore into Variants (name,description) values
  ('Alice', 'Both sides of the mirror'),
  ('Allmate', 'Mate any piece'),
  ('Antiking', 'Keep antiking in check'),
  ('Antimatter', 'Dangerous collisions'),
  ('Arena', 'Middle battle'),
  ('Atomic', 'Explosive captures'),
  ('Baroque', 'Exotic captures'),
  ('Benedict', 'Change colors'),
  ('Berolina', 'Pawns move diagonally'),
  ('Checkered', 'Shared pieces'),
  ('Check3', 'Give three checks'),
  ('Chess960', 'Standard rules'),
  ('Circular', 'Run forward'),
  ('Crazyhouse', 'Captures reborn'),
  ('Cylinder', 'Neverending rows'),
  ('Dark', 'In the shadow'),
  ('Enpassant', 'Capture en passant'),
  ('Extinction', 'Capture all of a kind'),
  ('Grand', 'Big board'),
  ('Grasshopper', 'Long jumps over pieces'),
  ('Hidden', 'Unidentified pieces'),
  ('Hiddenqueen', 'Queen disguised as a pawn'),
  ('Knightmate', 'Mate the knight'),
  ('Knightrelay', 'The knight transfers its powers'),
  ('Losers', 'Lose all pieces'),
  ('Magnetic', 'Laws of attraction'),
  ('Marseille', 'Move twice'),
  ('Rifle', 'Shoot pieces'),
  ('Royalrace', 'Kings cross the board'),
  ('Recycle', 'Reuse pieces'),
  ('Shatranj', 'Ancient rules'),
  ('Suction', 'Attract opposite king'),
  ('Upsidedown', 'Board upside down'),
  ('Wildebeest', 'Balanced sliders & leapers'),
  ('Wormhole', 'Squares disappear'),
  ('Zen', 'Reverse captures');
