-- Re-run this script after variants are added

insert or ignore into Variants (name,description) values
  ('Alice', 'Both sides of the mirror'),
  ('Allmate1', 'Mate any piece (v1)'),
  ('Allmate2', 'Mate any piece (v2)'),
  ('Antiking1', 'Keep antiking in check (v1)'),
  ('Antiking2', 'Keep antiking in check (v2)'),
  ('Antimatter', 'Dangerous collisions'),
  ('Arena', 'Middle battle'),
  ('Atomic', 'Explosive captures'),
  ('Baroque', 'Exotic captures'),
  ('Benedict', 'Change colors'),
  ('Berolina', 'Pawns move diagonally'),
  ('Cannibal', 'Capture powers'),
  ('Capture', 'Mandatory captures'),
  ('Checkered', 'Shared pieces'),
  ('Chess960', 'Standard rules'),
  ('Circular', 'Run forward'),
  ('Coregal', 'Two royal pieces'),
  ('Crazyhouse', 'Captures reborn'),
  ('Cylinder', 'Neverending rows'),
  ('Dark', 'In the shadow'),
  ('Eightpieces', 'Each piece is unique'),
  ('Enpassant', 'Capture en passant'),
  ('Extinction', 'Capture all of a kind'),
  ('Grand', 'Big board'),
  ('Grasshopper', 'Long jumps over pieces'),
  ('Hidden', 'Unidentified pieces'),
  ('Hiddenqueen', 'Queen disguised as a pawn'),
  ('Knightmate', 'Mate the knight'),
  ('Knightrelay1', 'Move like a knight (v1)'),
  ('Knightrelay2', 'Move like a knight (v2)'),
  ('Losers', 'Get strong at self-mate'),
  ('Magnetic', 'Laws of attraction'),
  ('Marseille', 'Move twice'),
  ('Perfect', 'Powerful pieces'),
  ('Racingkings', 'Kings cross the 8x8 board'),
  ('Rifle', 'Shoot pieces'),
  ('Recycle', 'Reuse pieces'),
  ('Royalrace', 'Kings cross the 11x11 board'),
  ('Rugby', 'Transform an essay'),
  ('Shatranj', 'Ancient rules'),
  ('Suicide', 'Lose all pieces'),
  ('Suction', 'Attract opposite king'),
  ('Threechecks', 'Give three checks'),
  ('Upsidedown', 'Board upside down'),
  ('Wildebeest', 'Balanced sliders & leapers'),
  ('Wormhole', 'Squares disappear'),
  ('Zen', 'Reverse captures');
